# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXsUlCkck9xSXgKUu_oJg73kEvHo5559

# Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

Some of the popular languages that Data Scientists use are:


1. Python
2. R
3. SQL

Some of the commonly used libraries used by Data Scientists include:


1. Pandas
2. NumPy
3. Matplotlib

| Data Science Tools |
|--------------------|
| Jupyter Notebook  |
| RStudio          |
| Apache Zeppelin  |

###Below are a few examples of evaluating arithmetic expressions in Python
"""

#This a simple arithmetic expression to mutiply then add integers
result = (3 * 4) + 5
print(result)

#This will convert 200 minutes to hours by diving by 60
minutes = 200
hours = minutes / 60
print(hours)

"""**Objectives:**

- List popular languages for Data Science  
- Plotting in RStudio
- Introduction to GitHub

##Name: Livya Li
"""